In [1]:
import torch

# Eigenvector, Eigen value
Explanation: https://youtu.be/PFDu9oVAE-g?t=117

As we can see in the next example, eigen value for each dimension is always `0j`.

For each matrix 2x2 we get 2 eigen values.

In [91]:
X = torch.rand((100, 2, 2)) * 100
X[0][0] = torch.tensor([0, 0])
X[0][1] = torch.tensor([0, 0])
for i in range(100):
	x = X[i]
	eigval, eigvec = torch.linalg.eig(x)
	print(x)
	print(eigval)
	print(eigval.imag, eigval.imag == 0)
	print("\n")
	

tensor([[0., 0.],
        [0., 0.]])
tensor([0.+0.j, 0.+0.j])
tensor([0., 0.]) tensor([True, True])


tensor([[74.8644, 61.2181],
        [31.5591, 91.8550]])
tensor([ 38.5919+0.j, 128.1276+0.j])
tensor([0., 0.]) tensor([True, True])


tensor([[87.5385, 80.2597],
        [83.6231, 63.6204]])
tensor([158.3719+0.j,  -7.2130+0.j])
tensor([0., 0.]) tensor([True, True])


tensor([[99.2172, 69.1620],
        [70.4406, 60.6781]])
tensor([152.3571+0.j,   7.5382+0.j])
tensor([0., 0.]) tensor([True, True])


tensor([[30.8772, 15.8084],
        [91.5207, 91.9120]])
tensor([ 12.6288+0.j, 110.1604+0.j])
tensor([0., 0.]) tensor([True, True])


tensor([[ 7.4342, 47.0722],
        [80.6805, 77.9899]])
tensor([-28.2973+0.j, 113.7215+0.j])
tensor([0., 0.]) tensor([True, True])


tensor([[28.0008, 68.0577],
        [33.5336, 25.8003]])
tensor([ 74.6858+0.j, -20.8847+0.j])
tensor([0., 0.]) tensor([True, True])


tensor([[24.7035, 90.6842],
        [ 8.2701, 64.9472]])
tensor([10.8422+0.j, 78.8085+0.j])
te

How can we explain this? Why is the imaginary part always 0?
