In [11]:
import torch

x = torch.arange(12, dtype=torch.float32)

print(x.shape)
print(x.numel())

torch.Size([12])
12


In [13]:
X = x.reshape(3, 4)
print(X.shape)
print(X)

torch.Size([3, 4])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


In [18]:
A = torch.zeros((2, 3, 4))
print(A.shape)
print(A.numel())
print(A)

torch.Size([2, 3, 4])
24
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [24]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
X, Y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]))

In [26]:
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [36]:
print(torch.randint(0, 2, (10,), dtype=torch.float32))
a = torch.empty(10,).uniform_(0, 1)  # generate a uniform random matrix with range [0, 1]
print(torch.bernoulli(a))

tensor([1., 1., 0., 0., 1., 0., 0., 1., 0., 1.])
tensor([1., 0., 0., 0., 1., 1., 0., 0., 0., 0.])


In [44]:
x = torch.tensor([[1, 2, 3, 4]])
y = torch.tensor([[5], [6], [7], [8]])
print(x)
print(y)
print(x@y)
print(y@x)

tensor([[1, 2, 3, 4]])
tensor([[5],
        [6],
        [7],
        [8]])
tensor([[70]])
tensor([[ 5, 10, 15, 20],
        [ 6, 12, 18, 24],
        [ 7, 14, 21, 28],
        [ 8, 16, 24, 32]])
