In [1]:
import torch
import numpy as np

Create 2x2 tensor

In [7]:
x = torch.tensor([[1,2],[3,4]])
print(x,x.shape,x.dtype,sep='\n')

tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])
torch.int64


Another example, notice the dtype changed to float32 instead of int64

In [9]:
x = torch.tensor([1.0,2,3,4])
print(x,x.shape,x.dtype,sep='\n')

tensor([1., 2., 3., 4.])
torch.Size([4])
torch.float32


Create tensor from 0 to 9 (excluding)

In [11]:
x = torch.arange(9)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

Create 2D tensor with ones in the main diagonal

In [16]:
y = torch.eye(3)
y2 = torch.eye(3,dtype=torch.bool)
y,y2

(tensor([[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]]),
 tensor([[ True, False, False],
         [False,  True, False],
         [False, False,  True]]))

Create random tensor of spesific size, from standard uniform distrobution, with mean 0 and variance 1

<img src="./img/standard-normal-distribution-1024x633.png" width="25%" height="25%">


In [21]:
z = torch.randn(size=[2, 3, 3])
z

tensor([[[ 1.0192,  0.6002, -1.0520],
         [ 1.1489, -0.5555,  0.3219],
         [-0.9949, -0.9598, -0.2899]],

        [[-0.2894, -0.2445,  0.0487],
         [ 2.0331,  1.3217,  0.1701],
         [-0.3032, -0.7068,  1.9967]]])

# Practice Questions
# 1

In [29]:
arr1 = [1, 2, 3]
arr2 = [4.5, 5.5, 6.6]


x = torch.tensor(arr1)
y = torch.tensor(arr2)

x, y

(tensor([1, 2, 3]), tensor([4.5000, 5.5000, 6.6000]))

You can't convert str, char array to tensor, you'll get error

# 2

Create 4D tensor with values that uniformly sampled from [0, 1] at the same probability

In [35]:
x = torch.randint(0, 2, (1,2,3,4))
x

tensor([[[[0, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]],

         [[1, 1, 1, 1],
          [1, 1, 0, 0],
          [1, 0, 0, 1]]]])

Another way

In [41]:
# Create probability distribution to generate 1 with probability p and generate 0 with probability 1-p
a = torch.empty(3, 3).uniform_(0, 1)  # generate a uniform random matrix with range [0, 1]
print(a)

# Then, give bernoulli the probabilities 'a' 
torch.bernoulli(a)

tensor([[0.2231, 0.2374, 0.3281],
        [0.3284, 0.0721, 0.0967],
        [0.2614, 0.0775, 0.3892]])


tensor([[1., 0., 1.],
        [0., 0., 0.],
        [1., 1., 0.]])

## How to sample from bernoulli

Probability to sample 1 is 75% and 0 is 25%

In [46]:
a = torch.full((3, 3), 0.75)
torch.bernoulli(a)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

Probability to samlpe 1 is 10% and 0 is 90%

In [59]:
a = torch.full((3, 3), 0.1)
torch.bernoulli(a)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 1., 0.]])