In [1]:
import torch
import numpy as np

### Basic tensor operators 
Add two tensors with same dimension

If same dimension, each cell is called with the operator with the same cell in the other tensor at the same place

In [2]:
x = torch.tensor([1, 2, 3, 4])
y = torch.tensor([5, 6, 7, 8])
print(x + y)

tensor([ 6,  8, 10, 12])


Additional operations:
* \-
* \*
* \/
* \*\*

In [4]:
print(x - y, x * y, x / y, x**y, sep='\n')

tensor([-4, -4, -4, -4])
tensor([ 5, 12, 21, 32])
tensor([0.2000, 0.3333, 0.4286, 0.5000])
tensor([    1,    64,  2187, 65536])


### Compare speed of tensor operator and for loop

Built in operator '*' is much faster (30 micro seconds) than for loop (732 miliseconds)

About 3000 times faster

In [9]:
x = torch.ones(size=(10**5,))
y = torch.randint(low=0,high=10,size=(10**5,))

In [10]:
%%timeit
x*y

30.1 µs ± 507 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [11]:
%%timeit
for i in range(x.numel()):
	x[i]*y[i]

732 ms ± 2.19 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### Matrix multiplication product

In [13]:
x = torch.tensor([1, 2, 3, 4])
y = torch.tensor([5, 6, 7, 8])
x = x.reshape(1,4)
y = y.reshape(4,1)
print(x,y,x@y,y@x,sep='\n')

tensor([[1, 2, 3, 4]])
tensor([[5],
        [6],
        [7],
        [8]])
tensor([[70]])
tensor([[ 5, 10, 15, 20],
        [ 6, 12, 18, 24],
        [ 7, 14, 21, 28],
        [ 8, 16, 24, 32]])


#### Same as above but with one dimension tensors

Output dimension is also reduced

Notice: we got above `tensor([[70]])` for `x@y` but we got `tensor(70)` for next code

In [14]:
x = torch.tensor([1, 2, 3, 4])
y = torch.tensor([5, 6, 7, 8])
print(x@y,x==1,sep='\n')

tensor(70)
tensor([ True, False, False, False])


### Tensor stuff: Norm, Mim, Sum

`tensor.norm()` - Returns the matrix norm or vector norm of a given tensor.

What is norm? It is a vector (or any other high dimension matrix) that is vertical to a plane (for 2D).

In [20]:
x = torch.ones(size=(3,))
y = torch.ones(size=(3,3))
z = torch.ones(size=(3,3,3))
print(x,y,z,sep="\n")
print("\n")
print(x.norm(),y.min(),z.sum(),sep='\n')

tensor([1., 1., 1.])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


tensor(1.7321)
tensor(1.)
tensor(27.)


## Matrix axis

In [27]:
x = torch.arange(24).reshape(2,3,4)
print(x,x.size())

z = x.sum(axis=0) # This adds the x[0] and x[1] (which is axis 0), and output is one dimension less than x
print(z,z.size())

w = x.sum(axis=1) # This adds the COLUMNS of x (axis 1)
print(w,w.size())

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]) torch.Size([2, 3, 4])
tensor([[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]]) torch.Size([3, 4])
tensor([[12, 15, 18, 21],
        [48, 51, 54, 57]]) torch.Size([2, 4])


# Question 1

In [31]:
x = torch.randint(0, 2, (100, 2, 2))
x 

tensor([[[0, 0],
         [1, 1]],

        [[0, 0],
         [0, 0]],

        [[1, 0],
         [1, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 1],
         [1, 1]],

        [[0, 0],
         [0, 0]],

        [[0, 0],
         [1, 0]],

        [[0, 0],
         [1, 0]],

        [[1, 1],
         [0, 1]],

        [[0, 0],
         [1, 1]],

        [[1, 0],
         [1, 1]],

        [[0, 1],
         [1, 1]],

        [[1, 0],
         [1, 0]],

        [[0, 0],
         [1, 0]],

        [[1, 0],
         [0, 1]],

        [[0, 1],
         [1, 1]],

        [[1, 0],
         [1, 1]],

        [[0, 0],
         [0, 1]],

        [[0, 0],
         [0, 1]],

        [[0, 1],
         [0, 1]],

        [[1, 0],
         [0, 0]],

        [[0, 1],
         [1, 0]],

        [[1, 0],
         [0, 0]],

        [[0, 1],
         [0, 0]],

        [[0, 1],
         [1, 0]],

        [[1, 0],
         [1, 0]],

        [[1, 0],
         [1, 0]],

        [[0, 0],
         [0

## Question 1.a

Calculate eigen value, vectors of each of the 2x2 matrix (100 matrixes in total).

What can you say about the imaginary coefficient? 

In [39]:
for i in range(x.size(0)):
	L, V = torch.linalg.eig(X[i, :, :])
	print("X = ", X[i, :, :])
	print("L = ", L)
	print("V = ", V)
	print("\n")

X =  tensor([[42.6654, 19.6967],
        [28.5740, 88.9102]])
L =  tensor([32.6599+0.j, 98.9157+0.j])
V =  tensor([[-0.8916+0.j, -0.3305+0.j],
        [ 0.4529+0.j, -0.9438+0.j]])


X =  tensor([[86.7157, 68.8832],
        [51.2583, 92.5036]])
L =  tensor([ 30.1184+0.j, 149.1010+0.j])
V =  tensor([[-0.7726+0.j, -0.7412+0.j],
        [ 0.6348+0.j, -0.6713+0.j]])


X =  tensor([[12.6916, 75.8406],
        [86.4248, 96.5938]])
L =  tensor([-36.5407+0.j, 145.8261+0.j])
V =  tensor([[-0.8388+0.j, -0.4950+0.j],
        [ 0.5445+0.j, -0.8689+0.j]])


X =  tensor([[92.2485, 16.3867],
        [75.1649, 74.0078]])
L =  tensor([119.3895+0.j,  46.8668+0.j])
V =  tensor([[ 0.5169+0.j, -0.3396+0.j],
        [ 0.8561+0.j,  0.9406+0.j]])


X =  tensor([[12.8889, 90.5241],
        [54.1312, 66.4348]])
L =  tensor([-35.2846+0.j, 114.6083+0.j])
V =  tensor([[-0.8828+0.j, -0.6648+0.j],
        [ 0.4698+0.j, -0.7470+0.j]])


X =  tensor([[38.9260, 41.7911],
        [30.6651, 61.9254]])
L =  tensor([12.8256

Imaginary coefficient is always 0 for this case.

Professor said:

תעשו ניתוח אנליטי לאיך מחשבים ערכים עצמיים למטריצות 2 על 2 ותחפשו מה הפתרון של הפולינום האופייני שם, ואם תציבו משתנים מקריים הדבר הזה אף פעם לא יהיה מרוכב

"ניתוח אנליטי של ערכים עצמיים"


He talked about random matricis

## Another way to solve this - much faster

In [52]:
eig = torch.linalg.eig(X)
L, V = eig
print(L.size(), V.size())
print("L=",L)
#print("V=",V)

torch.Size([100, 2]) torch.Size([100, 2, 2])
L= tensor([[ 32.6599+0.j,  98.9157+0.j],
        [ 30.1184+0.j, 149.1010+0.j],
        [-36.5407+0.j, 145.8261+0.j],
        [119.3895+0.j,  46.8668+0.j],
        [-35.2846+0.j, 114.6083+0.j],
        [ 12.8256+0.j,  88.0259+0.j],
        [124.7656+0.j, -35.8119+0.j],
        [-28.7476+0.j, 120.5354+0.j],
        [-52.1396+0.j, 127.6087+0.j],
        [-29.9231+0.j, 136.5456+0.j],
        [-72.4076+0.j, 106.7372+0.j],
        [ 11.2001+0.j,   1.7968+0.j],
        [ 65.7931+0.j,   9.4558+0.j],
        [ 57.4890+0.j,  65.1946+0.j],
        [131.2129+0.j, -37.1996+0.j],
        [100.4486+0.j, -12.3708+0.j],
        [  0.2230+0.j,  72.9395+0.j],
        [ 83.3774+0.j, -21.5954+0.j],
        [ -9.9609+0.j,  95.8353+0.j],
        [ 22.2558+0.j, 158.2512+0.j],
        [ 64.1782+0.j, -11.1871+0.j],
        [ 28.9153+0.j, 122.0181+0.j],
        [102.5745+0.j,  34.0780+0.j],
        [-26.9969+0.j, 120.4048+0.j],
        [108.5137+0.j,  22.7261+0.j],
  

# Question 1.b

נורמת פרוביניוס

Frobenius norm

In [62]:
print(torch.norm(X, p="fro"))
print(X.norm())

tensor(1177.2965)
tensor(1177.2965)


# Question 1.c

# Question 1.d

נורמת אינסוף

In [80]:
A=torch.rand((100, 2, 2))
print(A.norm()) # Regular norm

tensor(11.2499)
tensor([[4.3290e-02, 9.9433e-01],
        [4.2701e-01, 1.4567e-01],
        [2.4875e-01, 2.1852e-02],
        [7.6637e-01, 3.2515e-02],
        [4.8808e-02, 6.4502e-01],
        [9.9754e-02, 9.0652e-01],
        [9.7938e-01, 9.7286e-01],
        [8.7611e-02, 6.7346e-01],
        [2.3435e-01, 8.9047e-01],
        [1.3191e-01, 4.5490e-01],
        [4.4491e-01, 7.5670e-01],
        [8.1558e-01, 6.4788e-01],
        [5.3246e-01, 1.8263e-01],
        [4.1025e-01, 1.0547e-02],
        [5.2886e-01, 2.6772e-02],
        [7.9733e-01, 2.8434e-01],
        [7.7047e-01, 8.4740e-01],
        [6.2973e-02, 8.4545e-01],
        [5.9941e-01, 5.2938e-01],
        [1.0830e-01, 8.4129e-01],
        [3.4681e-01, 8.6055e-01],
        [2.9971e-01, 8.6350e-01],
        [5.6588e-01, 1.4703e-01],
        [4.4817e-01, 3.7698e-01],
        [2.4186e-01, 1.9608e-01],
        [5.6358e-01, 2.4767e-01],
        [8.0529e-02, 2.8078e-01],
        [6.5731e-01, 8.6725e-01],
        [5.5530e-01, 7.3975e-01]

In [95]:
# Professor's code:
print(A[:,:,0].norm(p=float("inf"))) # Infinity norm
print(A[:,:,1].norm(p=float("inf"))) # Infinity norm

tensor(0.9957)
tensor(0.9931)


In [83]:
for i in range(100):
	print(A[i, :, :].norm())

tensor(1.2400)
tensor(0.6114)
tensor(1.1423)
tensor(1.2930)
tensor(0.9549)
tensor(1.4629)
tensor(1.6778)
tensor(1.0205)
tensor(1.4773)
tensor(1.0802)
tensor(1.1517)
tensor(1.2702)
tensor(1.0681)
tensor(0.7266)
tensor(1.1871)
tensor(1.1482)
tensor(1.1499)
tensor(1.3185)
tensor(1.0193)
tensor(0.9645)
tensor(1.2966)
tensor(0.9529)
tensor(0.8773)
tensor(0.8762)
tensor(0.8345)
tensor(0.8606)
tensor(0.6331)
tensor(1.1591)
tensor(1.3817)
tensor(1.1309)
tensor(1.3900)
tensor(1.3258)
tensor(0.8156)
tensor(0.6976)
tensor(0.8827)
tensor(1.1506)
tensor(0.6132)
tensor(0.8457)
tensor(1.2277)
tensor(1.0194)
tensor(1.2924)
tensor(1.0619)
tensor(1.2740)
tensor(0.8606)
tensor(1.4415)
tensor(1.5729)
tensor(1.3322)
tensor(1.4198)
tensor(0.9158)
tensor(1.1145)
tensor(1.2354)
tensor(1.0148)
tensor(1.0106)
tensor(0.8351)
tensor(1.3642)
tensor(0.9675)
tensor(1.4001)
tensor(0.7333)
tensor(0.6114)
tensor(0.9198)
tensor(0.5022)
tensor(1.0824)
tensor(1.6017)
tensor(1.3074)
tensor(0.6250)
tensor(1.4697)
tensor(0.6