In [74]:
import torch
import numpy as np

In [75]:
x = torch.arange(10)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


### Access values like array

In [76]:
print(x[0])
print(x[-1])

tensor(0)
tensor(9)


### Access matrix

In [77]:
x = torch.arange(10).reshape(2,5)
print(x)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [78]:
print(x[1,2],x[0,-1],sep='\n')

tensor(7)
tensor(4)


### Set value of spesific cells in 3D tensors

In [79]:
y = torch.zeros(size=(2,3,4))
y[1,0,0] = -2  # 3D tensor
y[-1,-1,-1] = 1
print(y)

tensor([[[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],

        [[-2.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  1.]]])


### Slice tensor

Here, we set value of 100 for cells that their index is 1, index of the second dimension is 1 or 2, and index of the third dimension is 0,1,2,3, with jumps of 2. 

In [80]:
y[1,1:2,0:4:2]=100
print(y)

tensor([[[  0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.]],

        [[ -2.,   0.,   0.,   0.],
         [100.,   0., 100.,   0.],
         [  0.,   0.,   0.,   1.]]])


### Masks (boolean indexes)

Print cells that match predicate - <b>it will always return one dimension tensor!</b>

In [81]:
x = torch.arange(10).reshape(2,5)
print(x)
print(x>5)
print("Values:", x[x>2])

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[False, False, False, False, False],
        [False,  True,  True,  True,  True]])
Values: tensor([3, 4, 5, 6, 7, 8, 9])


# Question 1

Create uniform variable X

Create filled inf variable Y



In [82]:
X = torch.randint(-5, 5, (10, 10), dtype=torch.float)
Y = torch.full((10, 10), float('inf'))
print(X)
print(torch.where(X>0, X, Y))

tensor([[ 1.,  0., -1.,  2., -1.,  3., -1., -1.,  3.,  1.],
        [ 1., -4., -2.,  0.,  1.,  3.,  3.,  4., -1., -4.],
        [ 3., -2., -2., -2.,  4.,  4., -3., -2.,  4., -2.],
        [ 2., -4., -1., -1.,  2.,  3., -1.,  3.,  3., -5.],
        [-2.,  1.,  4.,  2., -1., -1., -1., -2., -3., -4.],
        [-3., -1., -2., -1.,  2., -1.,  2., -1.,  0., -2.],
        [-2., -3., -4.,  1., -3.,  3.,  4.,  2.,  0.,  0.],
        [ 1.,  3., -4.,  3.,  2.,  3.,  4., -5., -3.,  0.],
        [ 3., -1.,  4., -2.,  4.,  4.,  2.,  2., -4.,  4.],
        [-5., -4., -5., -1.,  1., -5.,  0.,  3.,  3.,  3.]])
tensor([[1., inf, inf, 2., inf, 3., inf, inf, 3., 1.],
        [1., inf, inf, inf, 1., 3., 3., 4., inf, inf],
        [3., inf, inf, inf, 4., 4., inf, inf, 4., inf],
        [2., inf, inf, inf, 2., 3., inf, 3., 3., inf],
        [inf, 1., 4., 2., inf, inf, inf, inf, inf, inf],
        [inf, inf, inf, inf, 2., inf, 2., inf, inf, inf],
        [inf, inf, inf, 1., inf, 3., 4., 2., inf, inf],
       

Another way, without creating 'Y'

In [83]:
X = torch.randint(-5, 5, (10, 10), dtype=torch.double)
print(X)
print(torch.where(X>0, X, float('inf')))

tensor([[ 0.,  4.,  3.,  0., -1.,  4.,  3., -3., -5., -1.],
        [-4., -4.,  4.,  3., -1.,  1.,  1., -3.,  2.,  2.],
        [-1., -1., -4., -2.,  3., -5., -2.,  3.,  1., -3.],
        [-5., -2.,  0.,  3., -5., -4., -5., -2.,  0.,  0.],
        [ 2., -5.,  0.,  0., -3.,  3., -1.,  3., -4., -5.],
        [-5.,  2.,  1.,  1., -1., -3.,  4.,  1.,  4.,  0.],
        [ 1.,  0.,  2.,  4.,  0.,  0., -3.,  4.,  0., -4.],
        [-2.,  0., -2.,  4.,  2., -4., -5., -5., -1.,  2.],
        [-4., -2., -1.,  2.,  0., -1.,  1., -2., -3.,  0.],
        [-3., -3.,  2.,  3.,  2., -1.,  1., -2.,  2., -4.]],
       dtype=torch.float64)
tensor([[inf, 4., 3., inf, inf, 4., 3., inf, inf, inf],
        [inf, inf, 4., 3., inf, 1., 1., inf, 2., 2.],
        [inf, inf, inf, inf, 3., inf, inf, 3., 1., inf],
        [inf, inf, inf, 3., inf, inf, inf, inf, inf, inf],
        [2., inf, inf, inf, inf, 3., inf, 3., inf, inf],
        [inf, 2., 1., 1., inf, inf, 4., 1., 4., inf],
        [1., inf, 2., 4., inf, inf

# Question 2

In [84]:
X = X.reshape((10, 5, 2))
print(X)
print("slice: ", X[1::2, 1::2, 1::2])

tensor([[[ 0.,  4.],
         [ 3.,  0.],
         [-1.,  4.],
         [ 3., -3.],
         [-5., -1.]],

        [[-4., -4.],
         [ 4.,  3.],
         [-1.,  1.],
         [ 1., -3.],
         [ 2.,  2.]],

        [[-1., -1.],
         [-4., -2.],
         [ 3., -5.],
         [-2.,  3.],
         [ 1., -3.]],

        [[-5., -2.],
         [ 0.,  3.],
         [-5., -4.],
         [-5., -2.],
         [ 0.,  0.]],

        [[ 2., -5.],
         [ 0.,  0.],
         [-3.,  3.],
         [-1.,  3.],
         [-4., -5.]],

        [[-5.,  2.],
         [ 1.,  1.],
         [-1., -3.],
         [ 4.,  1.],
         [ 4.,  0.]],

        [[ 1.,  0.],
         [ 2.,  4.],
         [ 0.,  0.],
         [-3.,  4.],
         [ 0., -4.]],

        [[-2.,  0.],
         [-2.,  4.],
         [ 2., -4.],
         [-5., -5.],
         [-1.,  2.]],

        [[-4., -2.],
         [-1.,  2.],
         [ 0., -1.],
         [ 1., -2.],
         [-3.,  0.]],

        [[-3., -3.],
         [ 2.,  